# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
        # General Vagrant VM configuration.
        config.vm.box = "geerlingguy/ubuntu1604"
        config.ssh.insert_key = false
        config.vm.synced_folder ".","/vagrant",disabled:true
        config.vm.provider :virtualbox do |v|
                v.memory = 256
                v.linked_clone = true
        end

        # Application server 1.
        config.vm.define "solr" do |app1|
                app1.vm.hostname = "solr-service.dev"
                app1.vm.network :private_network, ip: "192.168.60.10"
        end

        # Ansible provisioner.
        config.vm.provision :ansible do |ansible|
                ansible.playbook = "provisioning/playbook.yml"
                ansible.sudo = true
        end
end
