# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	# General Vagrant VM configuration.
	config.vm.box = "box-cutter/ubuntu1610-desktop"
	config.ssh.insert_key = false
	config.vm.synced_folder ".","/vagrant",disabled:true
	config.vm.provider :virtualbox do |v|
		v.memory = 2048
		v.linked_clone = true
		v.gui = true
	end

	# Start Ubuntu Host for docker host
	config.vm.define "dockhst1" do |dockhst1|
		dockhst1.vm.hostname = "docker-host-01.dev"
		dockhst1.vm.network :private_network, ip: "192.168.60.10"
	end

	# Ansible provisioner.
	config.vm.provision :ansible do |ansible|
		ansible.playbook = "provisioning/playbook.yml"
		ansible.sudo = true
	end
end
